version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: ermanake
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ermanake
      MYSQL_USER: use
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./Database/Respaldo:/docker-entrypoint-initdb.d  # Cargar automáticamente los archivos SQL
      - ./mysql_data:/var/lib/mysql                      # Volumen persistente de datos de MySQL
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
